apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce
stringData:
  # The keys we know it absolutely needs:
  root-password: "rootpassword"
  database: "ecommerce"
  
  # I am adding these two just in case the next line of your code asks for them. 
  # Extra keys won't hurt anything!
  username: "admin"
  password: "password"
