apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce
stringData:
  root-password: "rootpassword"
  database: "ecommerce"
  user: "admin"        # <-- We fixed this key!
  password: "password" # <-- Keeping this just in case it's next!
